require_dependency "dnu/process/module/before"
require_dependency "dnu/process/module/send_point"
require_dependency "dnu/process/module/send_item"
require_dependency "dnu/process/module/forge"
require_dependency "dnu/process/module/supplement"
require_dependency "dnu/process/module/equip"
require_dependency "dnu/process/module/train"
require_dependency "dnu/process/module/learn"
require_dependency "dnu/process/module/forget"
require_dependency "dnu/process/module/blossom"
require_dependency "dnu/process/module/grow"
require_dependency "dnu/process/module/move"
require_dependency "dnu/process/module/party"
require_dependency "dnu/process/module/notice"
require_dependency "dnu/process/module/map"
require_dependency "dnu/process/module/after"

require_dependency "dnu/process/update"
