- name: 合成
  caption: |-
    アイテム２つ(装備品を合成に指定する事は出来ない)を指定して別のアイテムを得る
    得られるアイテムは合成強度によって決定する
    ただし特定のアイテム同士を指定することで合成強度に関わらず特定のアイテムが得られる

- name: 付加
  caption: |-
    材料と装備品を指定して、材料を消費し、装備品の付加Bを変化させる
    付加Bが空欄の場合は材料の本来の効果が付加され、既に埋まってる場合は本来の効果と埋まってる効果によって付加Bが変化する

- name: 狩猟
  caption: |-
    宣言画面にて通常戦の相手を指定して、指定した相手からアイテムを得る権利が発生する
    LVに応じて得られるアイテムが変化する

- name: 釣匠
  caption: |-
    宣言画面にて釣糸を足らすか･餌を消費するかを決めて、その更新内でLVに応じたアイテムを得るか、次回の通常戦の相手が変化する
    この技能は水辺に隣接していないと宣言出来ない

- name: 園芸
  caption: |-
    宣言画面にて園芸を行うか･消耗を消費するかを決めて、次回の更新でLV、消費した消耗に応じてアイテムを得る
    ただし、薬師の技能で作製した消耗は消費出来ない

- name: 鍛治
  caption: |-
    宣言画面にて材料･作製する装備品の種類を指定して、指定した種類の装備品を作製する
    LVに応じて確率でG品(付加Aが本来の付加に加えて追加でもうひとつ)が完成する

- name: 解錠
  caption: |-
    宣言画面にて宝箱を指定し、LVに応じて罠にかかりづらくなる
    また、宣言画面にて材料を指定し、鍵(消耗)を作製する事が出来る
    譲渡可能で、使用者はその更新のみ鍵を作製した者の鍵を作製した時と同じLV扱いで解錠を行える

- name: 薬師
  caption: |-
    材料を消費して、消耗･戦物を作製する技能。
    材料によってLVが一定以上無いと失敗し作製出来ない。
