- name: 合成
  caption: |-
    材料、消耗のいずれか二つを混ぜ合わせて新たなアイテムを作製する生産技能です。
    LVが高いほど<b>様々なアイテムを作製出来ます</b>。
    また、特定のアイテムを混ぜ合わせた際、普段とは異なるアイテムが作製される場合があります。

- name: 開錠
  caption: |-
    戦闘終了後にまれに現れる宝箱を開けやすくする生産技能です。
    LVが高いほど<b>宝箱に仕掛けられた罠にかかりにくくなります</b>。

- name: 狩猟
  caption: |-
    戦闘終了後にたまに敵NPCからアイテムを取得出来る生産技能です。
    LVが高いほど<b>アイテムを取得出来る確率が増加します</b>。
    また、LVが一定以上の場合、<b>珍しいアイテムを取得出来る場合があります</b>。

- name: 薬師
  caption: |-
    材料を一つ消費して消耗、もしくは戦物を作製する生産技能です。
    LVが高いほど<b>様々なアイテムを用いて作製出来ます</b>。

- name: 釣匠
  caption: |-
    水辺に隣接している際に、水面に釣糸とかを垂らす生産技能です。
    LVが高いほど<b>質の良い何かが釣り糸に引っかかってくれます</b>。

- name: 改造
  caption: |-
    材料を一つ消費して装備品の付加効果Bを変化させる生産技能です。
    既に付加効果Bが存在している場合、別の付加効果に変化します。
    LVが高いほど<b>様々なアイテムを用いて改造出来ます</b>。

- name: 鍛冶
  caption: |-
    材料を一つ消費して装備品を作成する生産技能です。
    LVが高いほど<b>強さの値が高い装備品を作製出来ます</b>。
    また、まれに<b>性能が高い逸品を作製出来ます</b>。

- name: 園芸
  caption: |-
    持ち運び出来る何かに種とかを蒔いてアイテムを取得出来る生産技能です。
    園芸を行う際に消耗を一つ消費することで、取得出来るアイテムに影響を及ぼします。
    LVが高いほど<b>様々なアイテムを取得出来ます</b>。

- name: 探索
  caption: |-
    エリア移動"後"のマップを隈なく調べる行動です。
    生産技能としては存在せず、誰でもこの行動を行うことが出来ます。
    探索を行うことで、様々な事象が発生します。
    探索はマップ内のどこでも行えます。
