require_dependency "dnu/fight/state/character"

require_dependency "dnu/fight/state/character/base_character"
require_dependency "dnu/fight/state/character/pc"
require_dependency "dnu/fight/state/character/npc"
require_dependency "dnu/fight/state/character/dragon"
require_dependency "dnu/fight/state/character/puppet"

require_dependency "dnu/fight/state/value/base_value"
require_dependency "dnu/fight/state/value/mhp"
require_dependency "dnu/fight/state/value/mmp"
require_dependency "dnu/fight/state/value/hp"
require_dependency "dnu/fight/state/value/mp"
require_dependency "dnu/fight/state/value/at"
require_dependency "dnu/fight/state/value/mat"
require_dependency "dnu/fight/state/value/df"
require_dependency "dnu/fight/state/value/mdf"
require_dependency "dnu/fight/state/value/hit"
require_dependency "dnu/fight/state/value/mhit"
require_dependency "dnu/fight/state/value/eva"
require_dependency "dnu/fight/state/value/meva"
require_dependency "dnu/fight/state/value/spd"
