require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Register::CommunitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Register::Community. As you add validations to Register::Community, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Register::CommunitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all register_communities as @register_communities" do
      community = Register::Community.create! valid_attributes
      get :index, {}, valid_session
      assigns(:register_communities).should eq([community])
    end
  end

  describe "GET show" do
    it "assigns the requested register_community as @register_community" do
      community = Register::Community.create! valid_attributes
      get :show, {:id => community.to_param}, valid_session
      assigns(:register_community).should eq(community)
    end
  end

  describe "GET new" do
    it "assigns a new register_community as @register_community" do
      get :new, {}, valid_session
      assigns(:register_community).should be_a_new(Register::Community)
    end
  end

  describe "GET edit" do
    it "assigns the requested register_community as @register_community" do
      community = Register::Community.create! valid_attributes
      get :edit, {:id => community.to_param}, valid_session
      assigns(:register_community).should eq(community)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Register::Community" do
        expect {
          post :create, {:register_community => valid_attributes}, valid_session
        }.to change(Register::Community, :count).by(1)
      end

      it "assigns a newly created register_community as @register_community" do
        post :create, {:register_community => valid_attributes}, valid_session
        assigns(:register_community).should be_a(Register::Community)
        assigns(:register_community).should be_persisted
      end

      it "redirects to the created register_community" do
        post :create, {:register_community => valid_attributes}, valid_session
        response.should redirect_to(Register::Community.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved register_community as @register_community" do
        # Trigger the behavior that occurs when invalid params are submitted
        Register::Community.any_instance.stub(:save).and_return(false)
        post :create, {:register_community => { "user" => "invalid value" }}, valid_session
        assigns(:register_community).should be_a_new(Register::Community)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Register::Community.any_instance.stub(:save).and_return(false)
        post :create, {:register_community => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested register_community" do
        community = Register::Community.create! valid_attributes
        # Assuming there are no other register_communities in the database, this
        # specifies that the Register::Community created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Register::Community.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => community.to_param, :register_community => { "user" => "" }}, valid_session
      end

      it "assigns the requested register_community as @register_community" do
        community = Register::Community.create! valid_attributes
        put :update, {:id => community.to_param, :register_community => valid_attributes}, valid_session
        assigns(:register_community).should eq(community)
      end

      it "redirects to the register_community" do
        community = Register::Community.create! valid_attributes
        put :update, {:id => community.to_param, :register_community => valid_attributes}, valid_session
        response.should redirect_to(community)
      end
    end

    describe "with invalid params" do
      it "assigns the register_community as @register_community" do
        community = Register::Community.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Register::Community.any_instance.stub(:save).and_return(false)
        put :update, {:id => community.to_param, :register_community => { "user" => "invalid value" }}, valid_session
        assigns(:register_community).should eq(community)
      end

      it "re-renders the 'edit' template" do
        community = Register::Community.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Register::Community.any_instance.stub(:save).and_return(false)
        put :update, {:id => community.to_param, :register_community => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested register_community" do
      community = Register::Community.create! valid_attributes
      expect {
        delete :destroy, {:id => community.to_param}, valid_session
      }.to change(Register::Community, :count).by(-1)
    end

    it "redirects to the register_communities list" do
      community = Register::Community.create! valid_attributes
      delete :destroy, {:id => community.to_param}, valid_session
      response.should redirect_to(register_communities_url)
    end
  end

end
