profile:
  name:
    max: 20
  nickname:
    max: 10
  race:
    max: 20
  gender:
    max: 20
  age:
    max: 20
  introduction:
    max: 800

init_status:
  count:
    each: 5
    total: 15

register:
  history:
    options:
      -
        - 行動設定
        -
          -
            - 基本行動
            - mains
          -
            - 取引行動
            - trades
          -
            - 生産行動
            - products
      -
        - 戦闘設定
        -
          -
            - 通常戦
            - battles
          -
            - 手合わせ
            - duels
          -
            - 闘技大会
            - competitions
    per: 3

