party_slogan:
  slogan:
    maximum: 20

profile:
  name:
    maximum: 20
  nickname:
    maximum: 10
  race:
    maximum: 20
  gender:
    maximum: 20
  age:
    maximum: 20
  introduction:
    maximum: 800

init_status:
  counter:
    each_value: 5
    total: 15

register:
  history:
    per: 3

maximum:
  subject: 20
  name: 20
  caption: 800
  message: 800
  document: 1600
